#!/bin/sh
#
#   CDM: The Console Display Manager
#   A forked and stripped version of CDM by Paradigm0001
#
#   Copyright (C) 2009-2012, Daniel J Griffiths <dgriffiths@ghost1227.com>
#   Thanks to:
#
#       Andrwe          beta-testing and submitting the fix for the all
#                       important X incrementation function
#       brisbin33       code cleanup
#       tigrmesh        finding a critical issue with the gnome-session handler
#       Profjim         several incredibly useful patches
#       lambchops468    consolekit and hibernation patches
#       CasperVector    Massive rearchitecturing and code sanisation
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.
startxlog='/dev/null'

for arg; do
	case $arg in
		'--xrdb')
			shift
			# Call in the X server resource database
			xrdb="DISPLAY=$1 xrdb -load $HOME/.Xresources"
			shift
		;;
		'--startxlog')
			shift
			startxlog="$1"
			shift
		;;
		'--')
			shift
			break
		;;
	esac
done

# Start the X display
rm -f "$startxlog" 2>/dev/null
command -v neofetch >/dev/null 2>&1 && neofetch -L
[ -n "$xrdb" ] && until pidof Xorg; do
	eval $xrdb >/dev/null 2>&1
	sleep 0.66
done &
startx $@ > "$startxlog" 2>&1
