#!/bin/bash
#
# Example config file for cdm(1).
# Values set here is the default as in cdm(1).

# List of programs, commands with whitespaces should be quoted or escaped.
#
# (An example:)
# binlist=(
#   '~/.xsession'                    # Launch your X session,
#   '/bin/bash --login'              # or just execute your shell,
#   '/usr/bin/fbterm'                # or start a frame buffer console,
#   '/usr/bin/cdm ~/.submenu.cdmrc'  # or go to a submenu :)
# )

# List all program display names, one-by-one matched with $binlist.
# Names with whitespaces should be quoted or escaped.
#
# (Continued example:)
# namelist=('X session' Console FBTerm 'Sub menu')

# Type of the programs, one-by-one matched with $binlist.
# `C' for *C*onsole programs, which would be `exec'ed.
# `X' for *X* programs, which would be run with cdm-xlaunch(1).
#
# (Continued example:)
# flaglist=(X C C C)

# Style for the cdm dialog, which is printed with dialog(1).
# Default to unset, causing dialog(1) to use the system wide default.
# See /usr/share/doc/cdm/themes for some nice choices.
dialogrc=

# Index of the first item in the menu.
countfrom=0

# Set default display.
display=0

# Where should the first X tty be spawned?
# special value `keep' causes to run X in current tty.
xtty=7

# Should cdm(1) stick to the specified display?
locktty=no

# Additional arguments to pass to X server, which is usually called as:
#   /usr/bin/X :$display "${serverargs[@]}" vt$((xtty+display))
# Arguments with whitespaces should be quoted or escaped.
serverargs=(-nolisten tcp)

# Load the X server resource database
# Default is no for compatability with the typical behavior of cdm, HOWEVER
# it is recommended you enable this as most display managers load the X resources.
# If empty, default is no
xrdb=no

# Destination for stdout and stderr output from startx.
startxlog=/dev/null
